Contest4task s
Hramzik/algo_contests pull request #4
Opened 2023-10-22 12:59 UTC by Hramzik

2023-10-29 14:54 UTC, VladislavHacker requested changes

2023-10-29 14:54 UTC, VladislavHacker commented on src/s/task.cpp
> +    Solution solution (std::max (width, height), std::min (width, height));
max min это внутренняя часть реализации алгоритма, зачем пользователю об этом вообще думать?

2023-10-29 14:54 UTC, VladislavHacker commented on src/s/task.cpp
> +    int width = 0;
size_t

2023-10-29 14:54 UTC, VladislavHacker commented on src/s/task.cpp
> +#include <limits.h>
numeric limits

2023-10-29 14:54 UTC, VladislavHacker commented on src/s/task.cpp
> +void Solution::solve (void) {
название не говорит ни о чем

2023-10-29 14:54 UTC, VladislavHacker commented on src/s/task.cpp
> +LL Solution::count_dp (int x, Profile profile) {
dp-> назови со смыслом

2023-10-29 14:54 UTC, VladislavHacker commented on src/s/task.hpp
> +typedef unsigned long long ULL;
ЗАЧЕМ.

2023-12-14 18:26 UTC, Hramzik commented on src/s/task.hpp
> +    void solve (void);
вроде логично, что решатель решает

2023-12-14 18:28 UTC, Hramzik commented on src/s/task.hpp
> +    void pre_solve (void);
по спецификации гугла так можно писать, мне так больше нравится просто, так все объявления функций однообразные по структуре

2023-12-14 18:29 UTC, Hramzik commented on src/s/task.hpp
> +    int width_;
по спецификации гугла нужно писать int.
 In particular, do not use unsigned types to say a number will never be negative. Instead, use assertions for this.

2023-12-14 18:30 UTC, Hramzik commented on src/s/task.hpp
> +    int width_;
реально, поправил

2023-12-14 18:31 UTC, Hramzik commented on src/s/task.hpp
> +class Solution {
ну блин, решатель решает задачку
я даже не знаю как еще назвать

2023-12-14 18:32 UTC, Hramzik commented on src/s/task.cpp
> +    if (black_match & (black_match << 1)) return false;
кажется, так более читабельно

2023-12-14 18:33 UTC, Hramzik commented on src/s/task.hpp
> +    LL count_dp (int x, Profile profile);
ну у нас же тема контеста дп

2023-12-14 18:35 UTC, Hramzik commented on src/s/task.hpp
> +typedef unsigned long long Profile;
поменял

2023-12-14 18:36 UTC, Hramzik commented on src/s/task.hpp
> +    std::vector <bool> transitions_;
ну главное, что по tl зашло)

2023-12-14 18:36 UTC, Hramzik commented on src/s/task.cpp
> +    Solution solution (std::max (width, height), std::min (width, height));
реально, исправил

2023-12-14 18:37 UTC, Hramzik commented on src/s/task.cpp
> +    int width = 0;
выше ответил

2023-12-14 18:38 UTC, Hramzik commented on src/s/task.hpp
> +typedef unsigned long long ULL;
убрал)

2023-12-14 18:39 UTC, Hramzik commented on src/s/task.cpp
> +#include <limits.h>
оно тут вообще не нужно, так что убрал

2023-12-14 23:42 UTC, VladislavHacker commented on src/s/task.hpp
> +    void solve (void);
не логично 
что он решает, что ищет функция, давай std sort назовем std solve ? или "можно делать отсутствие дела"
https://youtu.be/fqWQ2tePQk8?feature=shared

2023-12-14 23:46 UTC, VladislavHacker commented on src/s/task.hpp
> +    LL count_dp (int x, Profile profile);
какой смысл содержит состояние?

2023-12-14 23:47 UTC, VladislavHacker commented on src/s/task.cpp
> +    int width = 0;
ок

2023-12-14 23:47 UTC, VladislavHacker commented on src/s/task.hpp
> +typedef unsigned long long ULL;
и почему не uint64_t?

2023-12-14 23:50 UTC, VladislavHacker requested changes

2023-12-14 23:50 UTC, VladislavHacker commented on src/s/task.hpp
> +class Solution {
ну господи, выбирай:
PatternCalculator
PatternCntSolver
PatternCounter

2023-12-14 23:50 UTC, VladislavHacker commented on src/s/task.hpp
> +    int width_;
ok

2023-12-18 10:18 UTC, VladislavHacker approved these changes
ну теперь можно принять

2024-02-23 10:17 UTC, merged