Contest4task n
Hramzik/algo_contests pull request #5
Opened 2023-10-22 12:59 UTC by Hramzik

2023-10-29 14:58 UTC, VladislavHacker requested changes

2023-10-29 14:58 UTC, VladislavHacker commented on src/n/task.cpp
> +int main (void) {
слишком большой мейн

2023-10-29 14:58 UTC, VladislavHacker commented on src/n/task.cpp
> +
???

2023-10-29 14:58 UTC, VladislavHacker commented on src/n/task.cpp
> +        long long accumulator = 0;
есть std accumulate

2023-10-29 14:58 UTC, VladislavHacker commented on src/n/task.cpp
> +            dp.pow (distance + 1);
не понятно что такое dp без дополнительных усилий

2023-10-29 14:58 UTC, VladislavHacker commented on src/n/task.cpp
> +            //std::cout << "fibonaci " << dp.x12_ << "\n";
удали ненужные комменты

2023-10-29 14:58 UTC, VladislavHacker commented on src/n/task.cpp
> +    for (int i = 0; i < (int) answer_.size (); ++i) {
static cast

2023-10-29 14:58 UTC, VladislavHacker commented on src/n/task.cpp
> +            accumulator += (dp.x12_ * port.flights_) % ANSWER_BY_MODULE;
лучше бы квадратные скобки )
а еще лучше чтоб у тебя была функция получающая числа фиббоначи

2023-10-29 14:58 UTC, VladislavHacker commented on src/n/task.cpp
> +void Solution::print_dp (void) {
хлам

2023-10-29 14:58 UTC, VladislavHacker commented on src/n/task.cpp
> +int Solution::recount_dp (int power, int min_number_power) {
опять хлам

2023-12-14 18:07 UTC, Hramzik commented on src/n/task.cpp
> +int main (void) {
ну тут же буквально только ввод данных

2023-12-14 18:08 UTC, Hramzik commented on src/n/task.cpp
> +
это подготовка к решению

2023-12-14 18:14 UTC, Hramzik commented on src/n/task.cpp
> +        long long accumulator = 0;
не совсем понимаю, как его тут применить. у нас же есть условное ветвление на 93 строчке

2023-12-14 18:18 UTC, Hramzik commented on src/n/task.cpp
> +
убрал кринжу

2023-12-14 18:20 UTC, Hramzik commented on src/n/task.cpp
> +            dp.pow (distance + 1);
добавил комментарий

2023-12-14 18:20 UTC, Hramzik commented on src/n/task.cpp
> +            //std::cout << "fibonaci " << dp.x12_ << "\n";
удалил

2023-12-14 18:21 UTC, Hramzik commented on src/n/task.cpp
> +    for (int i = 0; i < (int) answer_.size (); ++i) {
сделал

2023-12-14 18:23 UTC, Hramzik commented on src/n/task.cpp
> +            accumulator += (dp.x12_ * port.flights_) % ANSWER_BY_MODULE;
ну тогда уже нужно нормальную реализацию матрицы n на n писать,
но тут это излишне, кажется
ну тогда не будет dp))

2023-12-14 18:24 UTC, Hramzik commented on src/n/task.cpp
> +int Solution::recount_dp (int power, int min_number_power) {
убрал кринж

2023-12-14 18:24 UTC, Hramzik commented on src/n/task.cpp
> +void Solution::print_dp (void) {
убрал

2023-12-15 00:00 UTC, VladislavHacker requested changes

2023-12-15 00:00 UTC, VladislavHacker commented on src/n/task.hpp
> +    void print_result (void);
почему у тебя в солвере есть метод вывода
задача солвера вычислить ответ, с которым пользователь будет делать все что угодно

2023-12-15 00:00 UTC, VladislavHacker commented on src/n/task.cpp
> +#include <limits.h>
это тут нужно?

2023-12-15 00:00 UTC, VladislavHacker commented on src/n/task.cpp
> +#include "task.hpp"
назови файл в соответствии с задачей

2023-12-18 08:05 UTC, Hramzik commented on src/n/task.cpp
> +#include "task.hpp"
папка названа в честь задачи n, во всех папках файлы называются одинаково, чтобы makefile не переписывать

2023-12-18 10:20 UTC, VladislavHacker commented on src/n/task.cpp
> +#include "task.hpp"
ок

2023-12-18 10:22 UTC, VladislavHacker approved these changes

2024-02-23 10:19 UTC, merged