Зотов Владислав Б05-232 2 курс 92384537
Hramzik/algo_contests pull request #6
Opened 2023-10-22 13:00 UTC by Hramzik

2023-10-29 15:03 UTC, VladislavHacker requested changes
названия тоже подправь

2023-10-29 15:03 UTC, VladislavHacker commented on src/j/task.cpp
> +    for (int i = 0; i < ((int) string1.size () + 1) * ((int) string2.size () + 1); ++i) {
не используй сишный каст
в плюсах есть целых 4 вида кастов
выбери подходящий

2023-10-29 15:03 UTC, VladislavHacker commented on src/j/task.cpp
> +        dp.push_back (-1);
-1 is magic constant

2023-10-29 15:03 UTC, VladislavHacker commented on src/j/task.cpp
> +    for (int i = 0; i < (int) string1.size () + 1; ++i) {
мне кажется i проще size_t сделать

2023-10-29 15:03 UTC, VladislavHacker commented on src/j/task.cpp
> +void Solution::print_result (void) {
не выводи в решателе
он просто должен ответ возвращять

2023-12-14 18:01 UTC, Hramzik commented on src/j/task.cpp
> +Int_Pair::Int_Pair (int x, int y):
переименовал

2023-12-14 18:03 UTC, Hramzik commented on src/j/task.cpp
> +    for (int i = 0; i < ((int) string1.size () + 1) * ((int) string2.size () + 1); ++i) {
сделал static cast

2023-12-14 18:03 UTC, Hramzik commented on src/j/task.cpp
> +        dp.push_back (-1);
сделал bad_dp_value

2023-12-14 18:05 UTC, Hramzik commented on src/j/task.cpp
> +void Solution::print_result (void) {
так точно нельзя делать?
просто тогда придется отдельный класс для вывода писать

2023-12-15 00:05 UTC, VladislavHacker requested changes

2023-12-15 00:05 UTC, VladislavHacker commented on src/j/task.cpp
> +    solution.read_data ();
солвер не должен читать

2023-12-15 00:05 UTC, VladislavHacker commented on src/j/task.cpp
> +    solution.print_result ();
и выводить тоже

2023-12-15 00:05 UTC, VladislavHacker commented on src/j/task.cpp
> +    solution.pre_solve ();
что такое пре солве?

2023-12-15 00:05 UTC, VladislavHacker commented on src/j/task.cpp
> +    std::cin >> string1 >> string2;
почему этим занимается солвер?

2023-12-15 00:05 UTC, VladislavHacker commented on src/j/task.cpp
> +void Solution::print_result (void) {
функцию можно написать)
но в чем смысл решателя со своим принтом?

2023-12-15 00:05 UTC, VladislavHacker commented on src/j/task.cpp
> +static int Solution::bad_dp_value = -1;
твоя задача придумать как назвать класс так, чтобы было понятно какую задачу он решает

2023-12-15 00:05 UTC, VladislavHacker commented on src/j/task.cpp
> +    solution.pre_solve ();
и почему пользователь твоего класса должен знать о том что задача решается методом динамического программирования?

давай возьмем std sort и извратим его
solution.prepartirion()
solution.partirion()
solution.solve()
solution.print()

я утверждаю что мой код сортирует массив
Хотелось бы тебе пользоваться такой "сортировкой"?

2023-12-15 00:05 UTC, VladislavHacker commented on src/j/task.cpp
> +    //solution.print_dp ();
мусор

2023-12-18 10:23 UTC, VladislavHacker commented on src/j/task.cpp
> +    for (int i = 0; i < (int) string1.size () + 1; ++i) {
ну тогда каст нормальный выбери

2023-12-18 10:35 UTC, VladislavHacker requested changes

2023-12-18 10:35 UTC, VladislavHacker commented on src/j/task.cpp
> +void print_result (LcsFinder& solver);
у тебя результат это буквально вектор

2023-12-18 10:35 UTC, VladislavHacker commented on src/j/task.cpp
> +void print_lcs1 (LcsFinder& solver, int prefix1, int prefix2) {
в чем мем двух идентичных по коду функций
Возможно ли сделать одну функцию?

2023-12-18 10:35 UTC, VladislavHacker commented on src/j/task.cpp
> +        print_lcs1 (solver, prefix1 - 1, prefix2 - 1);
зачем тебе тут рекурсия

2023-12-18 10:35 UTC, VladislavHacker commented on src/j/task.cpp
> +    solver.solve ();
auto res = solver.solve ();

2023-12-18 10:35 UTC, VladislavHacker commented on src/j/task.cpp
> +    print_result (solver);
print_vector(res.first_sequence)
print_vector(res.second_sequence)

2023-12-18 10:35 UTC, VladislavHacker commented on src/j/task.cpp
> +void print_lcs1   (LcsFinder& solver, int prefix1, int prefix2);
и почему функция для вывода ответа занимается восстановлением результата?

2023-12-18 10:35 UTC, VladislavHacker commented on src/j/task.cpp
> +    answer_ = count_dp ((int) string1_.size (), (int) string2_.size ());
используй адекватные касты

2023-12-18 10:35 UTC, VladislavHacker commented on src/j/task.cpp
> +    return dp [index];
dp - жду также норм название

2023-12-18 10:35 UTC, VladislavHacker commented on src/j/task.hpp
> +    friend void print_result (LcsFinder& solver);
это явно кринж
почему нельзя просто вернуть lcs?

2023-12-18 10:35 UTC, VladislavHacker commented on src/j/task.hpp
> +    LcsFinder (std::string& string1, std::string& string2);
почему ссылки не константные?

2023-12-18 10:35 UTC, VladislavHacker commented on src/j/task.hpp
> +    void pre_solve (void);
зачем в классе тонна публичного мусора?
юзеру это все не нужно

2023-12-18 10:35 UTC, VladislavHacker commented on src/j/task.cpp
> +#include <limits.h>
это используется?

2023-12-18 10:35 UTC, VladislavHacker commented on src/j/task.cpp
> +    std::string string1; std::cin >> string1;
зачем писать две строки в одну?
ты переносы строк экономишь?

2023-12-18 10:35 UTC, VladislavHacker commented on src/j/task.cpp
> +    if (pair1.x_ != pair2.x_) return false;
return pair1.x_ == pair2.x_ && pair1.y_ == pair2.y_;

2023-12-18 10:35 UTC, VladislavHacker commented on src/j/task.cpp
> +bool operator== (Position pair1, Position pair2) {
Position pair1
мб pos1?
почему не по const ссылке а по копии?

2024-02-23 10:25 UTC, Hramzik commented on src/j/task.cpp
> +bool operator== (Position pair1, Position pair2) {
поправил

2024-02-23 10:25 UTC, Hramzik commented on src/j/task.cpp
> +    if (pair1.x_ != pair2.x_) return false;
мне т=нравится все разносить по случаям

2024-02-23 10:26 UTC, Hramzik commented on src/j/task.cpp
> +    std::string string1; std::cin >> string1;
поправил

2024-02-23 10:27 UTC, Hramzik commented on src/j/task.cpp
> +#include <limits.h>
убрал

2024-02-23 10:28 UTC, Hramzik commented on src/j/task.hpp
> +    void pre_solve (void);
убрал

2024-02-23 10:41 UTC, Hramzik commented on src/j/task.cpp
> +    print_result (solver);
сделал

2024-02-23 10:41 UTC, Hramzik commented on src/j/task.cpp
> +    solver.solve ();
да

2024-02-23 10:43 UTC, Hramzik commented on src/j/task.cpp
> +void print_lcs1 (LcsFinder& solver, int prefix1, int prefix2) {
там разные аргументы пушатся в разные массивы

2024-02-23 10:44 UTC, Hramzik commented on src/j/task.cpp
> +void print_result (LcsFinder& solver);
сделал

2024-02-23 13:58 UTC, VTroyanGolovyan approved these changes
стало лучше, но все еще лютый костыльмейкинг

2024-02-23 13:58 UTC, VTroyanGolovyan commented on src/j/task.hpp
> +    LcsFinderResult solve (void);
get_lcs ну что с неймингом)

2024-02-23 13:58 UTC, VTroyanGolovyan commented on src/j/task.hpp
> +    LcsFinder (std::string& string1, std::string& string2);
ССЫЛКИ НУЖНЫ КОНСТАНТНЫЕ

2024-02-23 13:58 UTC, VTroyanGolovyan commented on src/j/task.cpp
> +static void print_vector (std::vector <int>& vector) {
ссылка константная

2024-02-23 13:58 UTC, VTroyanGolovyan commented on src/j/task.cpp
> +        find_lcs2 (prefix1 - 1, prefix2 - 1);
на кой черт тут нужна рекурсия

2024-04-16 13:42 UTC, merged