correct branchB plasement
Hramzik/algo_contests pull request #7
Opened 2023-10-22 13:00 UTC by Hramzik

2023-10-29 15:07 UTC, VladislavHacker requested changes

2023-10-29 15:07 UTC, VladislavHacker commented on src/b/b.cpp
> +            std::cout << matrix.get (row, column) << " ";
stream :/

2023-10-29 15:07 UTC, VladislavHacker commented on src/b/b.hpp
> +    static const Matrix5x5 O;
назови матрицы нормально
ZeroMatrix
OnesMatrix?

2023-12-14 17:43 UTC, Hramzik commented on src/b/b.cpp
> +            std::cout << matrix.get (row, column) << " ";
?)

2023-12-14 17:44 UTC, Hramzik commented on src/b/b.hpp
> +    static const Matrix5x5 O;
сделал

2023-12-14 23:38 UTC, VladislavHacker requested changes

2023-12-14 23:38 UTC, VladislavHacker commented on src/b/b.cpp
> +            std::cout << matrix.get (row, column) << " ";
std::cout -> stream
иначе в чем смысл оператора?

2023-12-18 10:38 UTC, VladislavHacker approved these changes

2023-12-18 10:38 UTC, VladislavHacker commented on src/b/b.cpp
> +    //std::cout << assistance_matrix;
это че?

2023-12-18 10:38 UTC, VladislavHacker commented on src/b/b.hpp
> +    static const Matrix5x5 E;
вообще более общепринятое название это I
но квм вам читает E, так что ок

2024-02-23 10:19 UTC, merged