Зотов Владислав Б05-232 2 курс 98086089
Hramzik/algo_contests pull request #8
Opened 2023-12-14 17:38 UTC by Hramzik

2023-12-15 00:10 UTC, VladislavHacker requested changes

2023-12-15 00:10 UTC, VladislavHacker commented on src/d/task.cpp
> +        solution.add_edge (vertex1, vertex2);
откуда у солюшна появились ребра?
Он Адам?

2023-12-15 00:10 UTC, VladislavHacker commented on src/d/task.cpp
> +    Solution solution (vertex_count);
https://ru.wikipedia.org/wiki/SOLID_(программирование)
тебе явно надо почитать вот это вот

2023-12-15 00:10 UTC, VladislavHacker commented on src/d/task.cpp
> +        solution.add_edge (vertex1, vertex2);
Напиши нормальный класс графа
И внешнюю функцию/класс для алгоритма

2024-02-23 11:38 UTC, Hramzik commented
сделал граф, все пофиксил

2024-02-23 14:01 UTC, VTroyanGolovyan approved these changes
есть что менять но уже пойдет

2024-04-16 13:42 UTC, merged